In [68]:
# 1. importing necessary libraries
import pandas as pd# fro preparing dataframe
import numpy as np
import matplotlib.pyplot as plt # for visualizing clusters
from matplotlib import style
style.use("ggplot") # choosing the style for visualising clusters
from scipy.cluster.hierarchy import linkage,dendrogram #descriptive analytic 
from sklearn.cluster import KMeans #Descriptive analytic algorithm
from sklearn import preprocessing # for preparing data
from sklearn.preprocessing import Normalizer # For Normalizing data
from numpy import set_printoptions # for limiting number decimals
from sklearn.decomposition import PCA # for reducing attributes
from sklearn.model_selection import train_test_split





In [69]:
# 2. #extracting data
path='C:/Users/User/Desktop/Data/protein_file.csv'
attributes=['Molecular_Weight','Gravity','Aromaticity','Instability','Isoelectic_Point','Compartment']
data=pd.read_csv(path, names=attributes)
print(data)

     Molecular_Weight   Gravity  Aromaticity  Instability  Isoelectic_Point  \
0          93323.4594 -0.213571     0.075000    33.803119          5.995056   
1          27949.8955 -0.740000     0.077551    48.864980          4.799377   
2          17453.7134 -0.450327     0.098039    37.247124          6.489685   
3          35268.1468 -0.009366     0.063444    30.649245          8.177429   
4          25718.5138 -0.406912     0.142857    36.475576          8.082214   
5         120634.5465 -0.098273     0.088182    34.071391          6.960754   
6         250774.6466 -0.300983     0.082700    40.815919          5.869080   
7          36569.4096 -0.055917     0.082840    19.513609          7.596985   
8          25318.1366 -0.447727     0.081818    37.295909          8.694397   
9          48297.1855 -0.343678     0.071264    33.785310          8.733215   
10         42137.1258 -0.597855     0.107239    44.941019          6.640320   
11         58065.7220  0.008534     0.025974    36.7

In [70]:
# 3. Understanding Data
print(data.describe())

       Molecular_Weight     Gravity  Aromaticity  Instability  \
count        737.000000  737.000000   737.000000   737.000000   
mean       52690.435714   -0.344067     0.083136    39.390669   
std        46794.374331    0.283437     0.028133    12.130573   
min         7206.856600   -1.650602     0.000000    -6.006803   
25%        26584.215000   -0.503169     0.066667    32.434568   
50%        44151.288800   -0.328594     0.082203    38.924792   
75%        63830.392100   -0.182964     0.097065    44.941019   
max       538812.435500    1.224138     0.227586   113.656944   

       Isoelectic_Point  
count        737.000000  
mean           7.121456  
std            1.731533  
min            3.605530  
25%            5.655945  
50%            6.696594  
75%            8.681824  
max           11.814636  


In [71]:
print(data.info)

<bound method DataFrame.info of      Molecular_Weight   Gravity  Aromaticity  Instability  Isoelectic_Point  \
0          93323.4594 -0.213571     0.075000    33.803119          5.995056   
1          27949.8955 -0.740000     0.077551    48.864980          4.799377   
2          17453.7134 -0.450327     0.098039    37.247124          6.489685   
3          35268.1468 -0.009366     0.063444    30.649245          8.177429   
4          25718.5138 -0.406912     0.142857    36.475576          8.082214   
5         120634.5465 -0.098273     0.088182    34.071391          6.960754   
6         250774.6466 -0.300983     0.082700    40.815919          5.869080   
7          36569.4096 -0.055917     0.082840    19.513609          7.596985   
8          25318.1366 -0.447727     0.081818    37.295909          8.694397   
9          48297.1855 -0.343678     0.071264    33.785310          8.733215   
10         42137.1258 -0.597855     0.107239    44.941019          6.640320   
11         58065.722

In [72]:
# 4. Split Input and Output Features
TrainingSample,TestSample=train_test_split(data, test_size=0.3, random_state=2 ) #default is 25% starts at row number 2
print ("Training Set")
print(TrainingSample)
print("Testing Sample")
print(TestSample)

Training Set
     Molecular_Weight   Gravity  Aromaticity  Instability  Isoelectic_Point  \
658        29789.1132 -0.423792     0.078067    31.026022         10.234070   
479        93088.1911 -0.414100     0.080569    40.082109          8.028870   
134        22762.9771  0.073585     0.099057     6.573113          8.478577   
155        32033.7325 -0.505245     0.090909    18.920979          5.117004   
605        51214.9721 -0.337061     0.094298    38.928114          8.835266   
139        44896.3389 -0.087857     0.050000    30.260500          6.727600   
565        91286.1752 -0.396671     0.045623    32.770407          8.569153   
480        19988.3797 -0.506936     0.132948    14.610462          7.025696   
60         88091.3724 -0.765897     0.069231    49.022949          5.401794   
546        16020.5389 -0.501460     0.065693    54.546058          9.379211   
656        58062.1850 -0.056983     0.070764    31.448641          8.285583   
165        64520.4923 -0.647687     0.1

In [73]:
# 5. Splitting Input and Output Variables
# Slice the input variables Data
Training_InputVariables=TrainingSample.values[:,0:5]

# Slice the Output Variable Data
Training_OutputVariable=TrainingSample.values[:,5]
print("Input Variables of Training Data")
print (Training_InputVariables)
print("Output Variables of Training Data")
print (Training_OutputVariable)

Input Variables of Training Data
[[29789.1132 -0.42379182200000004 0.078066914 31.0260223 10.23406982]
 [93088.1911 -0.414099526 0.08056872 40.082109 8.028869628999999]
 [22762.9771 0.07358490599999999 0.099056604 6.573113208 8.47857666]
 ...
 [20666.927 -0.445303867 0.154696133 30.20939227 6.888000487999999]
 [60234.0316 -0.184934087 0.103578154 49.5194162 9.045593262]
 [77851.1107 -0.281129272 0.11887072800000001 41.49601783
  5.511047362999999]]
Output Variables of Training Data
['Mitochondria' 'Extracellular' 'Cytosol' 'Cytosol' 'Mitochondria'
 'Cytosol' 'Mitochondria' 'Extracellular' 'Cytosol' 'Mitochondria'
 'Mitochondria' 'Cytosol' 'Mitochondria' 'Extracellular' 'Mitochondria'
 'Cytosol' 'Extracellular' 'Cytosol' 'Mitochondria' 'Cytosol' 'Cytosol'
 'Cytosol' 'Extracellular' 'Mitochondria' 'Mitochondria' 'Cytosol'
 'Cytosol' 'Cytosol' 'Cytosol' 'Cytosol' 'Mitochondria' 'Cytosol'
 'Cytosol' 'Cytosol' 'Cytosol' 'Cytosol' 'Extracellular' 'Extracellular'
 'Cytosol' 'Extracellular' 'C

In [74]:
# 6. Splitting Test Input and Output Variables
# Slice the input variables Data
Test_InputVariables=TestSample.values[:,0:5]

# Slice the Output Variable Data
Test_OutputVariable=TestSample.values[:,5]
print("Input Variables of Test Data")
print (Test_InputVariables)
print("Output Variables of Test Data")
print (Test_OutputVariable)

Input Variables of Test Data
[[34582.6007 -0.08745874599999999 0.099009901 42.58353135
  7.625671387000001]
 [37027.1267 -0.339130435 0.102484472 36.50717391 6.669616699]
 [48618.9604 -0.19606986899999998 0.048034934 35.56266376 6.229675293]
 ...
 [240715.7448 -0.37157799 0.07276034599999999 33.61810368 4.79864502]
 [25107.0179 -0.15401785699999998 0.0625 94.121875 5.257385254]
 [28685.1228 0.039483395 0.081180812 24.80073801 5.737243652]]
Output Variables of Test Data
['Cytosol' 'Cytosol' 'Mitochondria' 'Extracellular' 'Cytosol'
 'Mitochondria' 'Extracellular' 'Mitochondria' 'Cytosol' 'Mitochondria'
 'Cytosol' 'Extracellular' 'Extracellular' 'Mitochondria' 'Cytosol'
 'Mitochondria' 'Cytosol' 'Extracellular' 'Extracellular' 'Extracellular'
 'Extracellular' 'Mitochondria' 'Extracellular' 'Cytosol' 'Cytosol'
 'Extracellular' 'Mitochondria' 'Mitochondria' 'Cytosol' 'Cytosol'
 'Cytosol' 'Mitochondria' 'Cytosol' 'Cytosol' 'Cytosol' 'Cytosol'
 'Extracellular' 'Mitochondria' 'Mitochondria' 'M

In [75]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
Training_InputVariables = sc.fit_transform(Training_InputVariables)
Test_InputVariables= sc.transform(Test_InputVariables)

C:\Users\User\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [76]:
# 6. Fitting Random Forest Classifier
# Loading Libraries
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
# Set random seed
#np.random.seed(0)
# Build a tree model of three layers

classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)




In [77]:
#7. Training The model
classifier.fit(Training_InputVariables, Training_OutputVariable)




RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=4, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [78]:
# 8. Predicting the Test set results

Testdata_pred = classifier.predict(Test_InputVariables)
print(Testdata_pred)

['Mitochondria' 'Cytosol' 'Cytosol' 'Cytosol' 'Extracellular'
 'Mitochondria' 'Cytosol' 'Mitochondria' 'Cytosol' 'Extracellular'
 'Cytosol' 'Cytosol' 'Cytosol' 'Mitochondria' 'Cytosol' 'Mitochondria'
 'Cytosol' 'Cytosol' 'Cytosol' 'Extracellular' 'Cytosol' 'Mitochondria'
 'Extracellular' 'Mitochondria' 'Extracellular' 'Extracellular' 'Cytosol'
 'Cytosol' 'Cytosol' 'Cytosol' 'Extracellular' 'Mitochondria' 'Cytosol'
 'Cytosol' 'Cytosol' 'Cytosol' 'Extracellular' 'Cytosol' 'Mitochondria'
 'Mitochondria' 'Cytosol' 'Cytosol' 'Mitochondria' 'Cytosol' 'Cytosol'
 'Cytosol' 'Extracellular' 'Mitochondria' 'Mitochondria' 'Mitochondria'
 'Cytosol' 'Cytosol' 'Cytosol' 'Extracellular' 'Cytosol' 'Mitochondria'
 'Mitochondria' 'Extracellular' 'Mitochondria' 'Cytosol' 'Cytosol'
 'Cytosol' 'Cytosol' 'Cytosol' 'Mitochondria' 'Cytosol' 'Mitochondria'
 'Cytosol' 'Cytosol' 'Cytosol' 'Extracellular' 'Mitochondria'
 'Mitochondria' 'Cytosol' 'Mitochondria' 'Extracellular' 'Extracellular'
 'Extracellular' 'Cyto

In [79]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Test_OutputVariable, Testdata_pred)
cm

array([[77, 12, 13],
       [29, 17,  5],
       [21,  6, 42]], dtype=int64)